#!/bin/bash

echo "Making a Backup of the original Cydia Icon..."

mv /Applications/Cydia.app/icon-72.png  /Applications/Cydia.app/icon-72.png.old
mv /Applications/Cydia.app/icon-72@2x.png  /Applications/Cydia.app/icon-72@2x.png.old
mv /Applications/Cydia.app/Icon-Small-50.png  /Applications/Cydia.app/Icon-Small-50.png.old
mv /Applications/Cydia.app/Icon-Small-50@2x.png  /Applications/Cydia.app/Icon-Small-50@2x.png.old
mv /Applications/Cydia.app/Icon-Small.png  /Applications/Cydia.app/Icon-Small.png.old
mv /Applications/Cydia.app/Icon-Small@2x.png  /Applications/Cydia.app/Icon-Small@2x.png.old
mv /Applications/Cydia.app/icon.png  /Applications/Cydia.app/icon.png.old
mv /Applications/Cydia.app/icon@2x.png  /Applications/Cydia.app/icon@2x.png.old
mv /Applications/Cydia.app/iconClassic.png  /Applications/Cydia.app/iconClassic.png.old

echo "Installing new icons..."

mv /tmp/cydiaicon1.png /Applications/Cydia.app/icon-72.png
mv /tmp/cydiaicon2.png /Applications/Cydia.app/icon-72@2x.png
mv /tmp/cydiaicon3.png /Applications/Cydia.app/Icon-Small-50.png
mv /tmp/cydiaicon4.png /Applications/Cydia.app/Icon-Small-50@2x.png
mv /tmp/cydiaicon5.png /Applications/Cydia.app/Icon-Small.png
mv /tmp/cydiaicon6.png /Applications/Cydia.app/Icon-Small@2x.png
mv /tmp/cydiaicon7.png /Applications/Cydia.app/icon.png
mv /tmp/cydiaicon8.png /Applications/Cydia.app/icon@2x.png
mv /tmp/cydiaicon9.png /Applications/Cydia.app/iconClassic.png


echo "Thank you for using Chir0student's Repository"
