#!/bin/bash

echo "Settings Permissions..."
chown root:wheel /Library/LaunchDaemons/com.openssh.sshd.plist
chmod 0644 /Library/LaunchDaemons/com.openssh.sshd.plist
echo "Unloading SSH daemon"
/bin/launchctl unload -w /Library/LaunchDaemons/com.openssh.sshd.plist
echo "Loading SSH daemon with bonjour enabled"
/bin/launchctl load -w /Library/LaunchDaemons/com.openssh.sshd.plist

exit 0
