all:
	gcc -L/opt/sdk/lib -L/var/sdk/lib -L/opt/lib -L/usr/local/lib -L/usr/lib -L/var/lib -L/lib -I/opt/sdk/include -I/var/sdk/include -I/var/include -I/usr/include -I/usr/local/include -I/var/include -I/var -I/usr/include/gnutls -I/usr/lib/ssl/include -I/usr/include/ncursesw -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/var/stash/include -I. -s -O2 pbasename.c -o pbasename
	@echo "Now copy the executable and the man page manually."
