#!/bin/bash

THEMES=/Library/Themes
LUMINOUS_MAIN="$THEMES"/Lumi\ Main\ Theme
APPICONMASK_RETINA_ORIG="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask\@2x~ipad.png
APPICONMASK_RETINA_NEW="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask\@2x~ipad_NEW.png
APPICONMASK_RETINA_OLD="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask\@2x~ipad_OLD.png
APPICONMASK_ORIG="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask~ipad.png
APPICONMASK_NEW="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask~ipad_NEW.png
APPICONMASK_OLD="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask~ipad_OLD.png
DEFAULTICON76_ORIG="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/DefaultIcon-76~ipad.png
DEFAULTICON76_NEW="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/DefaultIcon-76~ipad_NEW.png
DEFAULTICON76_OLD="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/DefaultIcon-76~ipad_OLD.png

if [ -e "$APPICONMASK_RETINA_OLD" ]; then
        mv "$APPICONMASK_RETINA_OLD" "$APPICONMASK_RETINA_NEW"
fi

if [ -e "$APPICONMASK_OLD" ]; then
        mv "$APPICONMASK_OLD" "$APPICONMASK_NEW"
fi

if [ -e "$DEFAULTICON76_OLD" ]; then
        mv "$DEFAULTICON76_OLD" "$DEFAULTICON76_NEW"
fi

exit 0
