#!/bin/bash


function IPAD_FIX () {

THEMES=/Library/Themes
LUMINOUS_MAIN="$THEMES"/Lumi\ Main\ Theme
APPICONMASK_RETINA_ORIG="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask\@2x~ipad.png
APPICONMASK_RETINA_NEW="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask\@2x~ipad_NEW.png
APPICONMASK_RETINA_OLD="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask\@2x~ipad_OLD.png
APPICONMASK_ORIG="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask~ipad.png
APPICONMASK_NEW="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask~ipad_NEW.png
APPICONMASK_OLD="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask~ipad_OLD.png
DEFAULTICON76_ORIG="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/DefaultIcon-76~ipad.png
DEFAULTICON76_NEW="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/DefaultIcon-76~ipad_NEW.png
DEFAULTICON76_OLD="$LUMINOUS_MAIN"/Bundles/com.apple.mobileicons.framework/DefaultIcon-76~ipad_OLD.png

if [ -e "$APPICONMASK_RETINA_ORIG" ]; then
	if [ -e "$APPICONMASK_RETINA_NEW" ]; then
		mv "$APPICONMASK_RETINA_ORIG" "$APPICONMASK_RETINA_OLD"
		mv "$APPICONMASK_RETINA_NEW" "$APPICONMASK_RETINA_ORIG"
	fi
fi

if [ -e "$APPICONMASK_ORIG" ]; then
	if [ -e "$APPICONMASK_NEW" ]; then
		mv "$APPICONMASK_ORIG" "$APPICONMASK_OLD"
		mv "$APPICONMASK_NEW" "$APPICONMASK_ORIG"
	fi
fi

if [ -e "$DEFAULTICON76_ORIG" ]; then
	if [ -e "$DEFAULTICON76_NEW" ]; then
		mv "$DEFAULTICON76_ORIG" "$DEFAULTICON76_OLD"
		mv "$DEFAULTICON76_NEW" "$DEFAULTICON76_ORIG"
	fi
fi

if [ -e "$APPICONMASK_RETINA_OLD" ]; then
	if [ -e "$APPICONMASK_OLD" ]; then
		if [ -e "$DEFAULTICON76_OLD" ]; then
			echo "Luminous iPad Overlay Fix was SUCCESSFUL!!"
		else
			echo "Please Reinstall Luminous <= v1.2, then Reinstall this package"
		fi
	else
		echo "Please Reinstall Luminous <= v1.2, then Reinstall this package"
	fi
else
	echo "Please Reinstall Luminous <= v1.2, then Reinstall this package"
fi
}

IPAD_FIX
