#!/bin/bash
echo "Wiping keyboard caches..."
rm -rf /private/var/mobile/Library/Caches/com.apple.keyboards

echo "Backing up emoji preferences into /Library/Emoji83"
if [ -f "/private/var/mobile/Library/Preferences/com.apple.EmojiPreferences.plist" ];then
        cp /private/var/mobile/Library/Preferences/com.apple.EmojiPreferences.plist /Library/Emoji83/com.apple.EmojiPreferences.plist
else
        echo "Could not find the preferences."
fi

echo "Done."

sleep 5

echo "BiteYourApple Repo"
echo "http://repo.biteyourapple.net"
