#!/bin/bash

#declare -a cydia
#cydia=($CYDIA)
#firmware=$(sw_vers -productVersion)

#if [[ $firmware == 8.0 || $firmware > 8.0 ]]; then
#    if [[ ${CYDIA+@} ]]; then
#        eval "echo 'finish:reboot' >&${cydia[0]}"
#    fi
#fi

echo
