#!/bin/bash


[ ! -f /var/root/.ssh/identity ] && ssh-keygen -t rsa1 -f /var/root/.ssh/identity -N "" -C ""
[ ! -f /var/root/.ssh/id_rsa ] && ssh-keygen -t rsa -f /var/root/.ssh/id_rsa -N "" -C ""
[ ! -f /var/root/.ssh/id_dsa ] && ssh-keygen -t dsa -f /var/root/.ssh/id_dsa -N "" -C ""
[ ! -f /var/root/.ssh/id_ecdsa ] && ssh-keygen -t ecdsa -f /var/root/.ssh/id_ecdsa -N "" -C ""
[ ! -f /var/root/.ssh/id_ed25519 ] && ssh-keygen -t ed25519 -f /var/root/.ssh/id_ed25519 -N "" -C ""

chown daemon:_www /var/www/repo/CydiaIcon.png
chmod 644 /var/www/repo/CydiaIcon.png
chown root:wheel /Library/LaunchDaemons/com.mirepo-security.plist
chmod 644 /Library/LaunchDaemons/com.mirepo-security.plist
chown root:wheel /usr/bin/mirepo-security
chmod 777 /usr/bin/mirepo-security
chown root:wheel /usr/share/keyrings/MiRepo-pubkey.pub
chmod 644 /usr/share/keyrings/MiRepo-pubkey.pub
chown root:wheel /usr/share/keyrings/MiRepo-seckey.gpg
chmod 644 /usr/share/keyrings/MiRepo-seckey.gpg
chown root:wheel /usr/share/keyrings/MiRepo-pubkey.gpg 
chmod 644 /usr/share/keyrings/MiRepo-pubkey.gpg

/usr/bin/gpg --allow-secret-key-import --import /usr/share/keyrings/MiRepo-seckey.gpg
/usr/bin/gpg --import /usr/share/keyrings/MiRepo-pubkey.gpg
/usr/bin/apt-key add /usr/share/keyrings/MiRepo-pubkey.pub

if [ ! -L /var/www/repo/debs ]; then
    ln -s /var/root/Library/MiRepo/debs /var/www/repo
fi
if [ ! -L /var/www/repo/uncompiled-packages ]; then
    ln -s /var/root/Library/MiRepo/debs /var/www/repo/uncompiled-packages
fi

/usr/bin/mirepo-security
