#!/bin/bash

echo "`cat /etc/hosts | grep cydia.mirepo.com | sed 's/#127.0.0.1 cydia.mirepo.com/127.0.0.1 cydia.mirepo.com/g'`" </etc/hosts
sleep 1
echo "Hosts file set"

server_dir="/var/www"

rm -rf "$server_dir"/Release.gpg
rm -rf "$server_dir"/Packages
rm -rf "$server_dir"/Packages.bz2
rm -rf "$server_dir"/Packages.gz