#!/bin/bash

THEMES=/Library/Themes
SAVANNAH_MAIN="$THEMES"/Savannah\ Main
APPICONMASK_RETINA_ORIG="$SAVANNAH_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask\@2x~ipad.png
APPICONMASK_RETINA_NEW="$SAVANNAH_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask\@2x~ipad_NEW.png
APPICONMASK_RETINA_OLD="$SAVANNAH_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask\@2x~ipad_OLD.png
APPICONMASK_ORIG="$SAVANNAH_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask~ipad.png
APPICONMASK_NEW="$SAVANNAH_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask~ipad_NEW.png
APPICONMASK_OLD="$SAVANNAH_MAIN"/Bundles/com.apple.mobileicons.framework/AppIconMask~ipad_OLD.png
DEFAULTICON76_ORIG="$SAVANNAH_MAIN"/Bundles/com.apple.mobileicons.framework/DefaultIcon-76~ipad.png
DEFAULTICON76_NEW="$SAVANNAH_MAIN"/Bundles/com.apple.mobileicons.framework/DefaultIcon-76~ipad_NEW.png
DEFAULTICON76_OLD="$SAVANNAH_MAIN"/Bundles/com.apple.mobileicons.framework/DefaultIcon-76~ipad_OLD.png

if [ -e "$APPICONMASK_RETINA_OLD" ]; then
        mv "$APPICONMASK_RETINA_OLD" "$APPICONMASK_RETINA_NEW"
fi

if [ -e "$APPICONMASK_OLD" ]; then
        mv "$APPICONMASK_OLD" "$APPICONMASK_NEW"
fi

if [ -e "$DEFAULTICON76_OLD" ]; then
        mv "$DEFAULTICON76_OLD" "$DEFAULTICON76_NEW"
fi

exit 0
