#!/bin/sh
sd=sudoers
cd /etc
if [[ -n `diff -q "$sd"_new $sd` ]];then
	mv $sd "$sd"_original
	mv "$sd"_new $sd
else
	echo "Already installed."
fi
chown root:wheel sudoer*
chmod 440 sudoer*
exit




	
	