#!/bin/bash

irt=/usr/local/bin/iRingtone
irtip6=/usr/local/bin/iRingtone-ip6.sh
irtip4=/usr/local/bin/iRingtone-ip4.sh
irtripad=/usr/local/bin/iRingtone-ipad.sh

chown root:wheel /usr/local/bin/iRingtone*
chmod 755 /usr/local/bin/iRingtone*

echo "Detecting device type..."
echo " "
sleep 1.5
echo "Linking..."
echo " "
sleep 1
echo "Setting permissions...."
echo " "
echo "Done!"
echo " "
if [ `sysctl -n hw.machine` = "iPhone7,1" ]; then
    ln -s "$irtip6" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone7,2" ]; then
    ln -s "$irtip6" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone6,2" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone6,1" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone5,4" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone5,3" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone5,2" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone5,1" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone4,1" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone3,3" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone3,2" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone3,1" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPhone2,1" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPod3,1" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPod4,1" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPod5,1" ]; then
    ln -s "$irtip4" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad1,1" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad2,1" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad2,2" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad2,3" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad2,4" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad3,1" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad3,2" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad3,3" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad3,4" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad3,5" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad3,6" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad4,1" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad4,2" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad4,3" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad4,4" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad4,5" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad4,6" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad4,7" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad4,8" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad4,9" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad5,3" ]; then
    ln -s "$irtripad" "$irt"
fi
if [ `sysctl -n hw.machine` = "iPad5,4" ]; then
    ln -s "$irtripad" "$irt"
fi

chown root:wheel /usr/local/bin/iRingtone
chmod 755 /usr/local/bin/iRingtone
echo
echo "Thank you for using iRingtone 4,"
echo "I really hope you like this."
echo
echo "Chir0student <chir0student@me.com>"
echo
exit 0
