#!/bin/bash

declare -a cydia
cydia=($CYDIA)

case "$1" in
  upgrade)
    if [[ ${CYDIA+@} ]]; then
          echo "Killing WhiteTerminal process..."
      killall WhiteTerminal
    fi
  ;;
esac

exit 0
