#!/bin/bash
if [ ! -e /usr/local/bin/perl ]; then
echo `mkdir -p /usr/local/lib;cd /usr/local/lib;ln -s /Applications/iRepo.app/Perl5 perl5`
fi

echo "RESPRING YOUR DEVICE AFTER INSTALLING IREPO!!!"
echo "RESPRING YOUR DEVICE AFTER INSTALLING IREPO!!!"
echo "RESPRING YOUR DEVICE AFTER INSTALLING IREPO!!!"
echo " "
echo "Cracked by Fabius"

exit 0
