#!/bin/bash

if [ -f /var/mobile/.gitconfig ]; then
    TGT1="/var/mobile/.gitconfig"
    cat $TGT1 | grep -v http | grep -v sslCAInfo $TGT1.new
    mv -f $TGT1 $TGT1.old
    mv -f $TGT1.new $TGT1
    chown mobile:mobile $TGT1
    chmod 644 $TGT1
fi

if [ -f /var/root/.gitconfig ]; then
    TGT2="/var/root/.gitconfig"
    cat $TGT2 | grep -v http | grep -v sslCAInfo $TGT2.new
    mv -f $TGT2 $TGT2.old
    mv -f $TGT2.new $TGT2
    chown root:wheel $TGT2
    chmod 644 $TGT2
fi

rm -rf /var/root/*.old
rm -rf /var/mobile/*.old
