#!/bin/bash

if [ -f /etc/ssl/certs/github-ssl-cert.crt ]; then
    su mobile -c "git config --global credential.helper store"
    su mobile -c "git config --global http.sslCAInfo /etc/ssl/certs/github-ssl-cert.crt"
    su mobile -c "git config --global color.ui true"
    su mobile -c "git config --global format.pretty oneline"
    su mobile -c "git config --global push.default matching"
else
    echo "...an error occurred."
    echo "The ssl cert file is missing from /etc/ssl/certs"
    echo "Please reinstall this package through Cydia."
fi
