#!/bin/bash

echo "Stopping iPod import service..."
kill `cat /var/mobile/Library/PwnTube/pt_ipodimport_daemon.pid`
if [ "$?" == "0" ]; then
	echo "Stopped successfully.";
else
	echo "Warning: could not stop iPod import daemon";
fi
exit 0

