#!/bin/bash

echo "Making a Backup of the original biteSMS Icon..."

mv /Applications/biteSMS.app/bite-menu.png  /Applications/biteSMS.app/bite-menu.png.old
mv /Applications/biteSMS.app/bite-menu@2x.png  /Applications/biteSMS.app/bite-menu@2x.png.old
mv /Applications/biteSMS.app/bite-nc.png  /Applications/biteSMS.app/bite-nc.png.old
mv /Applications/biteSMS.app/bite-nc@2x.png  /Applications/biteSMS.app/bite-nc@2x.png.old
mv /Applications/biteSMS.app/Icon-Small.png  /Applications/biteSMS.app/Icon-Small.png.old
mv /Applications/biteSMS.app/Icon-Small@2x.png  /Applications/biteSMS.app/Icon-Small@2x.png.old
mv /Applications/biteSMS.app/icon.png  /Applications/biteSMS.app/icon.png.old
mv /Applications/biteSMS.app/icon@2x.png  /Applications/biteSMS.app/icon@2x.png.old
mv /Applications/biteSMS.app/Lock-screen-QR.png  /Applications/biteSMS.app/Lock-screen-QR.png.old
mv /Applications/biteSMS.app/Lock-screen-QR@2x.png  /Applications/biteSMS.app/Lock-screen-QR@2x.png.old
mv /Applications/biteSMS.app/nc-qc-bite@2x.png  /Applications/biteSMS.app/nc-qc-bite@2x.png.old

echo "Installing new icons..."

mv /tmp/bitesms1.png /Applications/biteSMS.app/bite-menu.png
mv /tmp/bitesms2.png /Applications/biteSMS.app/bite-menu@2x.png
mv /tmp/bitesms3.png /Applications/biteSMS.app/bite-nc.png
mv /tmp/bitesms4.png /Applications/biteSMS.app/bite-nc@2x.png
mv /tmp/bitesms5.png /Applications/biteSMS.app/Icon-Small.png
mv /tmp/bitesms6.png /Applications/biteSMS.app/Icon-Small@2x.png
mv /tmp/bitesms7.png /Applications/biteSMS.app/icon.png
mv /tmp/bitesms8.png /Applications/biteSMS.app/icon@2x.png
mv /tmp/bitesms9.png /Applications/biteSMS.app/Lock-screen-QR.png
mv /tmp/bitesms10.png /Applications/biteSMS.app/Lock-screen-QR@2x.png
mv /tmp/bitesms11.png /Applications/biteSMS.app/nc-qc-bite@2x.png


echo "Thank you for using Chir0student's Repository"
