#!/bin/sh

# This script is executed AFTER the Debian package is REMOVED
# For information about this file, see http://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-maintscripts.

killall IPA_Installer

export IPA_INSTALLER_INFO_PLIST="/Applications/IPA_Installer.app/Info.plist"
export IPA_INSTALLER_BAK_PLIST="/Applications/IPA_Installer.app/Info.plist.bak"

if [ -e $IPA_INSTALLER_BAK_PLIST ]
then
    cp $IPA_INSTALLER_BAK_PLIST $IPA_INSTALLER_INFO_PLIST
    rm $IPA_INSTALLER_BAK_PLIST

    echo "Restored Info.plist file of IPA Installer"
fi