#!/bin/bash

echo "Linking local directory..."

if [ ! -L /usr/local ]; then
    echo "moving '/usr/local' to '/var/stash/local'"
    /usr/libexec/cydia/move.sh /usr/local
    echo "Linking local directory"
else
    echo "Directory structure is properly linked.
    echo "Cleaning up."
fi
echo " "
echo "Perl install complete."

exit 0
