#!/bin/sh

echo "Setting Permissions to 777..."
chmod 777 /usr/bin/ldone
chmod 777 /usr/bin/Rasticrac.sh
chmod 777 /usr/lib/RastDecrypted102.dylib
chmod 777 /usr/lib/RastDecrypted102.iOS7.dylib
echo "Permissions set"
echo "Please customize the script at /usr/bin/Rasticrac.sh"
echo "Any questions, please come to forum.iphonecake.com"

exit 0
