#!/bin/sh

if [ -f /var/lib/dpkg/info/ios-lighttpd-php-mysql.prerm ]
then
 patch -Ns -p1 /var/lib/dpkg/info/ios-lighttpd-php-mysql.prerm /etc/ios-lighttpd-php-mysql.prerm.patch
 rm /etc/ios-lighttpd-php-mysql.prerm.patch
fi

if [ -f /var/lib/dpkg/info/ios-lighttpd-php-mysql.prerm.rej ]
then
 rm /var/lib/dpkg/info/ios-lighttpd-php-mysql.prerm.rej
fi

exit 0
