#!/bin/bash

ORIG=/Library/Themes/Savannah\ Main/Info.plist
BACKUP=/Library/Themes/Savannah\ Main/Info_backup.plist
NEW=/Library/Themes/Savannah\ Main/Info_new.plist


if [ -f "$ORIG" ]; then
    mv "$ORIG" "$BACKUP"
    mv "$NEW" "$ORIG"
fi

exit 0
